import pkImg from '../../../public/image/countryImages/pak.png'
import sarImg from '../../../public/image/countryImages/saudia.png'
import serbiaImg from '../../../public/image/countryImages/serbia.png'
import seyImg from '../../../public/image/countryImages/Seychelles.png'
import singaporeImg from '../../../public/image/countryImages/Singapore.png'
import solomonImg from '../../../public/image/countryImages/SolomonIslands.png'
import sloveniaImg from '../../../public/image/countryImages/Slovenia.png'
import somaliaImg from '../../../public/image/countryImages/Somalia.png'
import southAfricaImg from '../../../public/image/countryImages/SouthAfrica.png'
import southKoreaImg from '../../../public/image/countryImages/SouthKorea.png'
import spainImg from '../../../public/image/countryImages/Spain.png'
import srilankaImg from '../../../public/image/countryImages/SriLanka.png'
import swedenImg from '../../../public/image/countryImages/Sweden.png'
import switzLandImg from '../../../public/image/countryImages/Switzerland.png'
import surinameImg from '../../../public/image/countryImages/Suriname.png'
import syriaImg from '../../../public/image/countryImages/Syria.png'
import taiwanImg from '../../../public/image/countryImages/Taiwan.png'
import thailandImg from '../../../public/image/countryImages/Thailand.png'
import tobagoImg from '../../../public/image/countryImages/TrinidadandTobago.png'
import turkeyImg from '../../../public/image/countryImages/Turkey.png'
import tuvaluImg from '../../../public/image/countryImages/Tuvalu.png'
import ukraineImg from '../../../public/image/countryImages/Ukraine.png'
import ukImg from '../../../public/image/countryImages/UnitedKingdom.png'
import usaImg from '../../../public/image/countryImages/UnitedStatesofAmerica.png'
import uruguayImg from '../../../public/image/countryImages/Uruguay.png'
import uzbekImg from '../../../public/image/countryImages/Uzbekistan.png'
import vaticanCityImg from '../../../public/image/countryImages/Thailand.png'
import venezuelaImg from '../../../public/image/countryImages/Venezuela.png'
import vietnamImg from '../../../public/image/countryImages/Vietnam.png'
import yemenImg from '../../../public/image/countryImages/Yemen.png'
import zimbabweImg from '../../../public/image/countryImages/Zimbabwe.png'
import iraqImg from '../../../public/image/countryImages/Iraq.png'
import kenyaImg from '../../../public/image/countryImages/Kenya.png'
import bangladeshImg from '../../../public/image/countryImages/Bangladesh.png'
import algerieImg from '../../../public/image/countryImages/Algerie.png'
import uaeImg from '../../../public/image/countryImages/UnitedArabEmirates.png'
import ugandaImg from '../../../public/image/countryImages/Uganda.png'
import tanzaniaImg from '../../../public/image/countryImages/Tanzania.png'
import angolaImg from '../../../public/image/countryImages/Angola.png'
import kuwaitImg from '../../../public/image/countryImages/Kuwait.png'
import bahrainImg from '../../../public/image/countryImages/Bahrain.png'



export const CURRENCY: any = [
  { key: "1", country: "Albania", currency: "Leke", code: "ALL", symbol: "Lek", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/al.png" },
  { key: "2", country: "America", currency: "Dollars", code: "USD", symbol: "$", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/um.png" },
  { key: "3", country: "Afghanistan", currency: "Afghanis", code: "AF", symbol: "؋", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: null, flag: null },
  { key: "4", country: "Argentina", currency: "Pesos", code: "ARS", symbol: "$", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/ar.png" },
  { key: "5", country: "Aruba", currency: "Guilders", code: "AWG", symbol: "ƒ", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/aw.png" },
  { key: "6", country: "Australia", currency: "Dollars", code: "AUD", symbol: "$", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/cc.png" },
  { key: "7", country: "Azerbaijan", currency: "New Manats", code: "AZ", symbol: "ман", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: null, flag: null },
  { key: "8", country: "Bahamas", currency: "Dollars", code: "BSD", symbol: "$", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/bs.png" },
  { key: "9", country: "Barbados", currency: "Dollars", code: "BBD", symbol: "$", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/bb.png" },
  { key: "10", country: "Belarus", currency: "Rubles", code: "BYR", symbol: "p.", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: null, flag: null },
  { key: "11", country: "Belgium", currency: "Euro", code: "EUR", symbol: "€", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/lt.png" },
  { key: "12", country: "Beliz", currency: "Dollars", code: "BZD", symbol: "BZ$", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/bz.png" },
  { key: "13", country: "Bermuda", currency: "Dollars", code: "BMD", symbol: "$", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/bm.png" },
  { key: "14", country: "Bolivia", currency: "Bolivianos", code: "BOB", symbol: "$b", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/bo.png" },
  { key: "15", country: "Bosnia and Herzegovina", currency: "Convertible Marka", code: "BAM", symbol: "KM", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/ba.png" },
  { key: "16", country: "Botswana", currency: "Pula's", code: "BWP", symbol: "P", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/bw.png" },
  { key: "17", country: "Bulgaria", currency: "Leva", code: "BG", symbol: "лв", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: null, flag: null },
  { key: "18", country: "Brazil", currency: "Reais", code: "BRL", symbol: "R$", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/br.png" },
  { key: "19", country: "Britain [United Kingdom]", currency: "Pounds", code: "GBP", symbol: "£", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/gg.png" },
  { key: "20", country: "Brunei Darussalam", currency: "Dollars", code: "BND", symbol: "$", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/bn.png" },
  { key: "21", country: "Cambodia", currency: "Riels", code: "KHR", symbol: "៛", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/kh.png" },
  { key: "22", country: "Canada", currency: "Dollars", code: "CAD", symbol: "$", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/ca.png" },
  { key: "23", country: "Cayman Islands", currency: "Dollars", code: "KYD", symbol: "$", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/ky.png" },
  { key: "24", country: "Chile", currency: "Pesos", code: "CLP", symbol: "$", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/cl.png" },
  { key: "25", country: "China", currency: "Yuan Renminbi", code: "CNY", symbol: "¥", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/cn.png" },
  { key: "26", country: "Colombia", currency: "Pesos", code: "COP", symbol: "$", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/co.png" },
  { key: "27", country: "Costa Rica", currency: "Colón", code: "CRC", symbol: "₡", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/cr.png" },
  { key: "28", country: "Croatia", currency: "Kuna", code: "HRK", symbol: "kn", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: null, flag: null },
  { key: "29", country: "Cuba", currency: "Pesos", code: "CUP", symbol: "₱", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: null, flag: null },
  { key: "30", country: "Cyprus", currency: "Euro", code: "EUR", symbol: "€", thousand_separator: ".", decimal_separator: ",", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/lt.png" },
  { key: "31", country: "Czech Republic", currency: "Koruny", code: "CZK", symbol: "Kč", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/cz.png" },
  { key: "32", country: "Denmark", currency: "Kroner", code: "DKK", symbol: "kr", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/dk.png" },
  { key: "33", country: "Dominican Republic", currency: "Pesos", code: "DOP ", symbol: "RD$", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/do.png" },
  { key: "34", country: "East Caribbean", currency: "Dollars", code: "XCD", symbol: "$", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/lc.png" },
  { key: "35", country: "Egypt", currency: "Pounds", code: "EGP", symbol: "£", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/eg.png" },
  { key: "36", country: "El Salvador", currency: "Colones", code: "SVC", symbol: "$", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: null, flag: null },
  { key: "37", country: "England [United Kingdom]", currency: "Pounds", code: "GBP", symbol: "£", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/gg.png" },
  { key: "38", country: "Euro", currency: "Euro", code: "EUR", symbol: "€", thousand_separator: ".", decimal_separator: ",", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/lt.png" },
  { key: "39", country: "Falkland Islands", currency: "Pounds", code: "FKP", symbol: "£", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/fk.png" },
  { key: "40", country: "Fiji", currency: "Dollars", code: "FJD", symbol: "$", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/fj.png" },
  { key: "41", country: "France", currency: "Euro", code: "EUR", symbol: "€", thousand_separator: ".", decimal_separator: ",", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/lt.png" },
  { key: "42", country: "Ghana", currency: "Cedis", code: "GHS", symbol: "¢", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/gh.png" },
  { key: "43", country: "Gibraltar", currency: "Pounds", code: "GIP", symbol: "£", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/gi.png" },
  { key: "44", country: "Greece", currency: "Euro", code: "EUR", symbol: "€", thousand_separator: ".", decimal_separator: ",", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/lt.png" },
  { key: "45", country: "Guatemala", currency: "Quetzales", code: "GTQ", symbol: "Q", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/gt.png" },
  { key: "46", country: "Guernsey", currency: "Pounds", code: "GGP", symbol: "£", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: null, flag: null },
  { key: "47", country: "Guyana", currency: "Dollars", code: "GYD", symbol: "$", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/gy.png" },
  { key: "48", country: "Holland [Netherlands]", currency: "Euro", code: "EUR", symbol: "€", thousand_separator: ".", decimal_separator: ",", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/lt.png" },
  { key: "49", country: "Honduras", currency: "Lempiras", code: "HNL", symbol: "L", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/hn.png" },
  { key: "50", country: "Hong Kong", currency: "Dollars", code: "HKD", symbol: "$", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/hk.png" },
  { key: "51", country: "Hungary", currency: "Forint", code: "HUF", symbol: "Ft", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/hu.png" },
  { key: "52", country: "Iceland", currency: "Kronur", code: "ISK", symbol: "kr", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/is.png" },
  { key: "53", country: "India", currency: "Rupees", code: "INR", symbol: "₹", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/in.png" },
  { key: "54", country: "Indonesia", currency: "Rupiahs", code: "IDR", symbol: "Rp", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/id.png" },
  { key: "55", country: "Iran", currency: "Rials", code: "IRR", symbol: "﷼", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/ir.png" },
  { key: "56", country: "Ireland", currency: "Euro", code: "EUR", symbol: "€", thousand_separator: ".", decimal_separator: ",", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/lt.png" },
  { key: "57", country: "Isle of Man", currency: "Pounds", code: "IMP", symbol: "£", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: null, flag: null },
  { key: "58", country: "Israel", currency: "New Shekels", code: "ILS", symbol: "₪", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/il.png" },
  { key: "59", country: "Italy", currency: "Euro", code: "EUR", symbol: "€", thousand_separator: ".", decimal_separator: ",", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/lt.png" },
  { key: "60", country: "Jamaica", currency: "Dollars", code: "JMD", symbol: "J$", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/jm.png" },
  { key: "61", country: "Japan", currency: "Yen", code: "JPY", symbol: "¥", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/jp.png" },
  { key: "62", country: "Jersey", currency: "Pounds", code: "JEP", symbol: "£", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: null, flag: null },
  { key: "63", country: "Kazakhstan", currency: "Tenge", code: "KZT", symbol: "лв", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/kz.png" },
  { key: "64", country: "Korea [North]", currency: "Won", code: "KPW", symbol: "₩", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/kp.png" },
  { key: "65", country: "Korea [South]", currency: "Won", code: "KRW", symbol: "₩", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/kr.png" },
  { key: "66", country: "Kyrgyzstan", currency: "Soms", code: "KGS", symbol: "лв", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/kg.png" },
  { key: "67", country: "Laos", currency: "Kips", code: "LAK", symbol: "₭", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/la.png" },
  { key: "68", country: "Latvia", currency: "Lati", code: "LVL", symbol: "Ls", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: null, flag: null },
  { key: "69", country: "Lebanon", currency: "Pounds", code: "LBP", symbol: "£", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/lb.png" },
  { key: "70", country: "Liberia", currency: "Dollars", code: "LRD", symbol: "$", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/lr.png" },
  { key: "71", country: "Liechtenstein", currency: "Switzerland Francs", code: "CHF", symbol: "CHF", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/li.png" },
  { key: "72", country: "Lithuania", currency: "Litai", code: "LTL", symbol: "Lt", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: null, flag: null },
  { key: "73", country: "Luxembourg", currency: "Euro", code: "EUR", symbol: "€", thousand_separator: ".", decimal_separator: ",", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/lt.png" },
  { key: "74", country: "Macedonia", currency: "Denars", code: "MKD", symbol: "ден", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/mk.png" },
  { key: "75", country: "Malaysia", currency: "Ringgits", code: "MYR", symbol: "RM", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/my.png" },
  { key: "76", country: "Malta", currency: "Euro", code: "EUR", symbol: "€", thousand_separator: ".", decimal_separator: ",", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/lt.png" },
  { key: "77", country: "Mauritius", currency: "Rupees", code: "MUR", symbol: "₨", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/mu.png" },
  { key: "78", country: "Mexico", currency: "Pesos", code: "MXN", symbol: "$", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/mx.png" },
  { key: "79", country: "Mongolia", currency: "Tugriks", code: "MNT", symbol: "₮", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/mn.png" },
  { key: "80", country: "Mozambique", currency: "Meticais", code: "MZ", symbol: "MT", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: null, flag: null },
  { key: "81", country: "Namibia", currency: "Dollars", code: "NAD", symbol: "$", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/na.png" },
  { key: "82", country: "Nepal", currency: "Rupees", code: "NPR", symbol: "₨", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/np.png" },
  { key: "83", country: "Netherlands Antilles", currency: "Guilders", code: "ANG", symbol: "ƒ", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/sx.png" },
  { key: "84", country: "Netherlands", currency: "Euro", code: "EUR", symbol: "€", thousand_separator: ".", decimal_separator: ",", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/lt.png" },
  { key: "85", country: "New Zealand", currency: "Dollars", code: "NZD", symbol: "$", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/tk.png" },
  { key: "86", country: "Nicaragua", currency: "Cordobas", code: "NIO", symbol: "C$", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/ni.png" },
  { key: "87", country: "Nigeria", currency: "Nairas", code: "NGN", symbol: "₦", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/ng.png" },
  { key: "88", country: "North Korea", currency: "Won", code: "KPW", symbol: "₩", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/kp.png" },
  { key: "89", country: "Norway", currency: "Krone", code: "NOK", symbol: "kr", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/sj.png" },
  { key: "90", country: "Oman", currency: "Rials", code: "OMR", symbol: "﷼", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/om.png" },
  { key: "91", country: "Pakistan", currency: "Rupees", code: "PKR", symbol: "₨", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/pk.png" },
  { key: "92", country: "Panama", currency: "Balboa", code: "PAB", symbol: "B\/.", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/pa.png" },
  { key: "93", country: "Paraguay", currency: "Guarani", code: "PYG", symbol: "Gs", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/py.png" },
  { key: "94", country: "Peru", currency: "Nuevos Soles", code: "PE", symbol: "S\/.", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: null, flag: null },
  { key: "95", country: "Philippines", currency: "Pesos", code: "PHP", symbol: "Php", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/ph.png" },
  { key: "96", country: "Poland", currency: "Zlotych", code: "PL", symbol: "zł", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: null, flag: null },
  { key: "97", country: "Qatar", currency: "Rials", code: "QAR", symbol: "﷼", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/qa.png" },
  { key: "98", country: "Romania", currency: "New Lei", code: "RO", symbol: "lei", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: null, flag: null },
  { key: "99", country: "Russia", currency: "Rubles", code: "RUB", symbol: "руб", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/ru.png" },
  { key: "100", country: "Saint Helena", currency: "Pounds", code: "SHP", symbol: "£", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/gs.png" },
  { key: "101", country: "Saudi Arabia", currency: "Riyals", code: "SAR", symbol: "﷼", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/sa.png" },
  { key: "102", country: "Serbia", currency: "Dinars", code: "RSD", symbol: "Дин.", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/rs.png" },
  { key: "103", country: "Seychelles", currency: "Rupees", code: "SCR", symbol: "₨", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/sc.png" },
  { key: "104", country: "Singapore", currency: "Dollars", code: "SGD", symbol: "$", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/sg.png" },
  { key: "105", country: "Slovenia", currency: "Euro", code: "EUR", symbol: "€", thousand_separator: ".", decimal_separator: ",", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/lt.png" },
  { key: "106", country: "Solomon Islands", currency: "Dollars", code: "SBD", symbol: "$", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/sb.png" },
  { key: "107", country: "Somalia", currency: "Shillings", code: "SOS", symbol: "S", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/so.png" },
  { key: "108", country: "South Africa", currency: "Rand", code: "ZAR", symbol: "R", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/za.png" },
  { key: "109", country: "South Korea", currency: "Won", code: "KRW", symbol: "₩", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/kr.png" },
  { key: "110", country: "Spain", currency: "Euro", code: "EUR", symbol: "€", thousand_separator: ".", decimal_separator: ",", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/lt.png" },
  { key: "111", country: "Sri Lanka", currency: "Rupees", code: "LKR", symbol: "₨", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/lk.png" },
  { key: "112", country: "Sweden", currency: "Kronor", code: "SEK", symbol: "kr", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/se.png" },
  { key: "113", country: "Switzerland", currency: "Francs", code: "CHF", symbol: "CHF", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/li.png" },
  { key: "114", country: "Suriname", currency: "Dollars", code: "SRD", symbol: "$", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/sr.png" },
  { key: "115", country: "Syria", currency: "Pounds", code: "SYP", symbol: "£", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/sy.png" },
  { key: "116", country: "Taiwan", currency: "New Dollars", code: "TWD", symbol: "NT$", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/tw.png" },
  { key: "117", country: "Thailand", currency: "Baht", code: "THB", symbol: "฿", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/th.png" },
  { key: "118", country: "Trinidad and Tobago", currency: "Dollars", code: "TTD", symbol: "TT$", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/tt.png" },
  { key: "119", country: "Turkey", currency: "Lira", code: "TRY", symbol: "TL", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/tr.png" },
  { key: "120", country: "Turkey", currency: "Liras", code: "TRL", symbol: "£", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: null, flag: null },
  { key: "121", country: "Tuvalu", currency: "Dollars", code: "TVD", symbol: "$", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: null, flag: null },
  { key: "122", country: "Ukraine", currency: "Hryvnia", code: "UAH", symbol: "₴", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/ua.png" },
  { key: "123", country: "United Kingdom", currency: "Pounds", code: "GBP", symbol: "£", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/gg.png" },
  { key: "124", country: "United States of America", currency: "Dollars", code: "USD", symbol: "$", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/um.png" },
  { key: "125", country: "Uruguay", currency: "Pesos", code: "UYU", symbol: "$U", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/uy.png" },
  { key: "126", country: "Uzbekistan", currency: "Sums", code: "UZS", symbol: "лв", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/uz.png" },
  { key: "127", country: "Vatican City", currency: "Euro", code: "EUR", symbol: "€", thousand_separator: ".", decimal_separator: ",", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/lt.png" },
  { key: "128", country: "Venezuela", currency: "Bolivares Fuertes", code: "VEF", symbol: "Bs", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: null, flag: null },
  { key: "129", country: "Vietnam", currency: "Dong", code: "VND", symbol: "₫", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/vn.png" },
  { key: "130", country: "Yemen", currency: "Rials", code: "YER", symbol: "﷼", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/ye.png" },
  { key: "131", country: "Zimbabwe", currency: "Zimbabwe Dollars", code: "ZWD", symbol: "Z$", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: null, flag: null },
  { key: "132", country: "Iraq", currency: "Iraqi dinar", code: "IQD", symbol: "د.ع", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/iq.png" },
  { key: "133", country: "Kenya", currency: "Kenyan shilling", code: "KES", symbol: "KSh", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/ke.png" },
  { key: "134", country: "Bangladesh", currency: "Taka", code: "BDT", symbol: "৳", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/bd.png" },
  { key: "135", country: "Algerie", currency: "Algerian dinar", code: "DZD", symbol: "د.ج", thousand_separator: " ", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/eh.png" },
  { key: "136", country: "United Arab Emirates", currency: "United Arab Emirates dirham", code: "AED", symbol: "د.إ", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/ae.png" },
  { key: "137", country: "Uganda", currency: "Uganda shillings", code: "UGX", symbol: "USh", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/ug.png" },
  { key: "138", country: "Tanzania", currency: "Tanzanian shilling", code: "TZS", symbol: "TSh", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/tz.png" },
  { key: "139", country: "Angola", currency: "Kwanza", code: "AOA", symbol: "Kz", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/ao.png" },
  { key: "140", country: "Kuwait", currency: "Kuwaiti dinar", code: "KWD", symbol: "KD", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:31", flag: "https:\/\/flagcdn.com\/w320\/kw.png" },
  { key: "141", country: "Bahrain", currency: "Bahraini dinar", code: "BHD", symbol: "BD", thousand_separator: ",", decimal_separator: ".", created_at: null, updated_at: "2023-02-16 18:25:32", flag: "https:\/\/flagcdn.com\/w320\/bh.png" }

  // {
  //   key: "91",
  //   name: "Rupees",
  //   country: "Pakistan",
  //   code: "PKR",
  //   symbol: "₨",
  //   // countryImage: 'assets/countryImages/pak.png',
  //   countryImage: pkImg,
  //   timeZone: 'Asia/Karachi'
  // },
  // {
  //   key: "101",
  //   name: "Riyals",
  //   country: "Saudi Arabia",
  //   code: "SAR",
  //   symbol: "﷼",
  //   countryImage: sarImg,
  //   timeZone: 'Asia/Riyadh'
  // },
  // {
  //   key: "102",
  //   name: "Dinars",
  //   country: "Serbia",
  //   code: "RSD",
  //   symbol: "Дин",
  //   countryImage: serbiaImg,
  //   timeZone: 'Europe/Belgrade'
  // },
  // {
  //   key: "103",
  //   name: "Rupees",
  //   country: "Seychelles",
  //   code: "SCR",
  //   symbol: "₨",
  //   countryImage: seyImg,
  //   timeZone: 'Indian/Mahe'
  // },
  // {
  //   key: "104",
  //   name: "Dollars",
  //   country: "Singapore",
  //   code: "SGD",
  //   symbol: "\$",
  //   countryImage: singaporeImg,
  //   timeZone: '	Asia/Singapore'
  // },
  // {
  //   key: "105",
  //   name: "Euro",
  //   country: "Slovenia",
  //   code: "EUR",
  //   symbol: "€",
  //   countryImage: sloveniaImg,
  //   timeZone: '	Europe/Ljubljana'
  // },
  // {
  //   key: "106",
  //   name: "Dollars",
  //   country: "Solomon Islands",
  //   code: "SBD",
  //   symbol: "\$",
  //   countryImage: solomonImg,
  //   timeZone: 'Pacific/Guadalcanal'
  // },
  // {
  //   key: "107",
  //   country: "Somalia",
  //   code: "SOS",
  //   symbol: "S",
  //   name: "Shillings",
  //   countryImage: somaliaImg,
  //   timeZone: 'Africa/Mogadishu'
  // },
  // {
  //   key: "108",
  //   name: "Rand",
  //   country: "South Africa",
  //   code: "ZAR",
  //   symbol: "R",
  //   countryImage: southAfricaImg,
  //   timeZone: 'Africa/Johannesburg'
  // },
  // {
  //   key: "109",
  //   name: "Won",
  //   country: "South Korea",
  //   code: "KRW",
  //   symbol: "₩",
  //   countryImage: southKoreaImg,
  //   timeZone: 'Asia/Seoul'
  // },
  // {
  //   key: "110",
  //   name: "Euro",
  //   country: "Spain",
  //   code: "EUR",
  //   symbol: "€",
  //   countryImage: spainImg,
  //   timeZone: 'Europe/Madrid'
  // },
  // {
  //   key: "111",
  //   name: "Rupees",
  //   country: "Sri Lanka",
  //   code: "LKR",
  //   symbol: "₨",
  //   countryImage: srilankaImg,
  //   timeZone: 'Asia/Colombo'
  // },
  // {
  //   key: "112",
  //   name: "Kronor",
  //   country: "Sweden",
  //   code: "SEK",
  //   symbol: "kr",
  //   countryImage: swedenImg,
  //   timeZone: 'Europe/Stockholm'
  // },
  // {
  //   key: "113",
  //   name: "Francs",
  //   country: "Switzerland",
  //   code: "CHF",
  //   symbol: "CHF",
  //   countryImage: switzLandImg,
  //   timeZone: 'Europe/Zurich'
  // },
  // {
  //   key: "114",
  //   name: "Dollars",
  //   country: "Suriname",
  //   code: "SRD",
  //   symbol: "\$",
  //   countryImage: surinameImg,
  //   timeZone: 'America/Paramaribo'
  // },
  // {
  //   key: "115",
  //   name: "Pounds",
  //   country: "Syria",
  //   code: "SYP",
  //   symbol: "£",
  //   countryImage: syriaImg,
  //   timeZone: 'Asia/Damascus'
  // },
  // {
  //   key: "116",
  //   name: "New Dollars",
  //   country: "Taiwan",
  //   code: "TWD",
  //   symbol: "NT\$",
  //   countryImage: taiwanImg,
  //   timeZone: 'Asia/Taipei'
  // },
  // {
  //   key: "117",
  //   name: "Baht",
  //   country: "Thailand",
  //   code: "THB",
  //   symbol: "฿",
  //   countryImage: thailandImg,
  //   timeZone: '	Asia/Bangkok'
  // },
  // {
  //   key: "118",
  //   name: "Dollars",
  //   country: "Trinidad and Tobago",
  //   code: "TTD",
  //   symbol: "TT\$",
  //   countryImage: tobagoImg,
  //   timeZone: 'America/Port_of_Spain'
  // },
  // {
  //   key: "119",
  //   name: "Lira",
  //   country: "Turkey",
  //   code: "TRY",
  //   symbol: "TL",
  //   countryImage: turkeyImg,
  //   timeZone: 'Europe/Istanbul'
  // },
  // {
  //   key: "120",
  //   name: "Liras",
  //   country: "Turkey",
  //   code: "TRL",
  //   symbol: "£",
  //   countryImage: turkeyImg,
  //   timeZone: 'Europe/Istanbul'
  // },
  // {
  //   key: "121",
  //   name: "Dollars",
  //   country: "Tuvalu",
  //   code: "TVD",
  //   symbol: "\$",
  //   countryImage: tuvaluImg,
  //   timeZone: 'Pacific/Funafuti'
  // },
  // {
  //   key: "122",
  //   name: "Hryvnia",
  //   country: "Ukraine",
  //   code: "UAH",
  //   symbol: "₴",
  //   countryImage: ukraineImg,
  //   timeZone: '	Europe/Simferopol'
  // },
  // {
  //   key: "123",
  //   name: "Pounds",
  //   country: "United Kingdom",
  //   code: "GBP",
  //   symbol: "£",
  //   countryImage: ukImg,
  //   timeZone: 'Europe/London'
  // },
  // {
  //   key: "124",
  //   name: "Dollars",
  //   country: "United States of America",
  //   code: "USD",
  //   symbol: "\$",
  //   countryImage: usaImg,
  //   timeZone: 'America/Los_Angeles'
  // },
  // {
  //   key: "125",
  //   name: "Pesos",
  //   country: "Uruguay",
  //   code: "UYU",
  //   symbol: "\$U",
  //   countryImage: uruguayImg,
  //   timeZone: 'America/Montevideo'
  // },
  // {
  //   key: "126",
  //   name: "Sums",
  //   country: "Uzbekistan",
  //   code: "UZS",
  //   symbol: "лв",
  //   countryImage: uzbekImg,
  //   timeZone: 'Asia/Tashkent'
  // },
  // {
  //   key: "127",
  //   name: "Euro",
  //   country: "Vatican City",
  //   code: "EUR",
  //   symbol: "€",
  //   countryImage: vaticanCityImg,
  //   timeZone: 'Europe/Vatican'
  // },
  // {
  //   key: "128",
  //   name: "Bolivares Fuertes",
  //   country: "Venezuela",
  //   code: "VEF",
  //   symbol: "Bs",
  //   countryImage: venezuelaImg,
  //   timeZone: 'America/Caracas'
  // },
  // {
  //   key: "129",
  //   name: "Dong",
  //   country: "Vietnam",
  //   code: "VND",
  //   symbol: "₫",
  //   countryImage: vietnamImg,
  //   timeZone: '	Asia/Ho_Chi_Minh'
  // },
  // {
  //   key: "130",
  //   name: "Rials",
  //   country: "Yemen",
  //   code: "YER",
  //   symbol: "﷼",
  //   countryImage: yemenImg,
  //   timeZone: 'Asia/Aden'
  // },
  // {
  //   key: "131",
  //   name: "Zimbabwe Dollars",
  //   country: "Zimbabwe",
  //   code: "ZWD",
  //   symbol: "Z\$",
  //   countryImage: zimbabweImg,
  // },
  // {
  //   key: "132",
  //   name: "Iraqi dinar",
  //   country: "Iraq",
  //   code: "IQD",
  //   symbol: "د.ع",
  //   countryImage: iraqImg,
  //   timeZone: 'Asia/Baghdad'
  // },
  // {
  //   key: "133",
  //   name: "Kenyan shilling",
  //   country: "Kenya",
  //   code: "KES",
  //   symbol: "KSh",
  //   countryImage: kenyaImg,
  //   timeZone: 'Africa/Nairobi'
  // },
  // {
  //   key: "134",
  //   name: "Taka",
  //   country: "Bangladesh",
  //   code: "BDT",
  //   symbol: "৳",
  //   countryImage: bangladeshImg,
  //   timeZone: '	Asia/Dhaka'
  // },
  // {
  //   key: "135",
  //   name: "Algerian dinar",
  //   country: "Algerie",
  //   code: "DZD",
  //   symbol: "د.ج",
  //   countryImage: algerieImg,
  //   timeZone: 'Africa/Algiers'
  // },
  // {
  //   key: "136",
  //   name: "United Arab Emirates dirham",
  //   country: "United Arab Emirates",
  //   code: "AED",
  //   symbol: "د.إ",
  //   countryImage: uaeImg,
  //   timeZone: 'Asia/Dubai'
  // },
  // {
  //   key: "137",
  //   name: "Uganda shillings",
  //   country: "Uganda",
  //   code: "UGX",
  //   symbol: "USh",
  //   countryImage: ugandaImg,
  //   timeZone: 'Africa/Kampala'
  // },
  // {
  //   key: "138",
  //   name: "Tanzanian shilling",
  //   country: "Tanzania",
  //   code: "TZS",
  //   symbol: "TSh",
  //   countryImage: tanzaniaImg,
  //   timeZone: 'Africa/Dar_es_Salaam'
  // },
  // {
  //   key: "139",
  //   name: "Kwanza",
  //   country: "Angola",
  //   code: "AOA",
  //   symbol: "Kz",
  //   countryImage: angolaImg,
  //   timeZone: '	Africa/Luanda'
  // },
  // {
  //   key: "140",
  //   name: "Kuwaiti dinar",
  //   country: "Kuwait",
  //   code: "KWD",
  //   symbol: "KD",
  //   countryImage: kuwaitImg,
  //   timeZone: 'Asia/Kuwait'
  // },
  // {
  //   key: "141",
  //   name: "Bahraini dinar",
  //   country: "Bahrain",
  //   code: "BHD",
  //   symbol: "BD",
  //   countryImage: bahrainImg,
  //   timeZone: 'Asia/Bahrain'
  // }
];

export const TIMEZONE: any = [
  { key: 'Africa/Abidjan', name: 'Africa/Abidjan' },
  { key: 'Africa/Accra', name: 'Africa/Accra' },
  { key: 'Africa/Addis_Ababa', name: 'Africa/Addis_Ababa' },
  { key: 'Africa/Algiers', name: 'Africa/Algiers' },
  { key: 'Africa/Asmara', name: 'Africa/Asmara' },
  { key: 'Africa/Bamako', name: 'Africa/Bamako' },
  { key: 'Africa/Bangui', name: 'Africa/Bangui' },
  { key: 'Africa/Banjul', name: 'Africa/Banjul' },
  { key: 'Africa/Bissau', name: 'Africa/Bissau' },
  { key: 'Africa/Blantyre', name: 'Africa/Blantyre' },
  { key: 'Africa/Brazzaville', name: 'Africa/Brazzaville' },
  { key: 'Africa/Bujumbura', name: 'Africa/Bujumbura' },
  { key: 'Africa/Cairo', name: 'Africa/Cairo' },
  { key: 'Africa/Casablanca', name: 'Africa/Casablanca' },
  { key: 'Africa/Ceuta', name: 'Africa/Ceuta' },
  { key: 'Africa/Conakry', name: 'Africa/Conakry' },
  { key: 'Africa/Dakar', name: 'Africa/Dakar' },
  { key: 'Africa/Dar_es_Salaam', name: 'Africa/Dar_es_Salaam' },
  { key: 'Africa/Djibouti', name: 'Africa/Djibouti' },
  { key: 'Africa/Douala', name: 'Africa/Douala' },
  { key: 'Africa/El_Aaiun', name: 'Africa/El_Aaiun' },
  { key: 'Africa/Freetown', name: 'Africa/Freetown' },
  { key: 'Africa/Gaborone', name: 'Africa/Gaborone' },
  { key: 'Africa/Harare', name: 'Africa/Harare' },
  { key: 'Africa/Johannesburg', name: 'Africa/Johannesburg' },
  { key: 'Africa/Juba', name: 'Africa/Juba' },
  { key: 'Africa/Kampala', name: 'Africa/Kampala' },
  { key: 'Africa/Khartoum', name: 'Africa/Khartoum' },
  { key: 'Africa/Kigali', name: 'Africa/Kigali' },
  { key: 'Africa/Kinshasa', name: 'Africa/Kinshasa' },
  { key: 'Africa/Lagos', name: 'Africa/Lagos' },
  { key: 'Africa/Libreville', name: 'Africa/Libreville' },
  { key: 'Africa/Lome', name: 'Africa/Lome' },
  { key: 'Africa/Luanda', name: 'Africa/Luanda' },
  { key: 'Africa/Lubumbashi', name: 'Africa/Lubumbashi' },
  { key: 'Africa/Lusaka', name: 'Africa/Lusaka' },
  { key: 'Africa/Malabo', name: 'Africa/Malabo' },
  { key: 'Africa/Maputo', name: 'Africa/Maputo' },
  { key: 'Africa/Maseru', name: 'Africa/Maseru' },
  { key: 'Africa/Mbabane', name: 'Africa/Mbabane' },
  { key: 'Africa/Mogadishu', name: 'Africa/Mogadishu' },
  { key: 'Africa/Monrovia', name: 'Africa/Monrovia' },
  { key: 'Africa/Nairobi', name: 'Africa/Nairobi' },
  { key: 'Africa/Ndjamena', name: 'Africa/Ndjamena' },
  { key: 'Africa/Niamey', name: 'Africa/Niamey' },
  { key: 'Africa/Nouakchott', name: 'Africa/Nouakchott' },
  { key: 'Africa/Ouagadougou', name: 'Africa/Ouagadougou' },
  { key: 'Africa/Porto-Novo', name: 'Africa/Porto-Novo' },
  { key: 'Africa/Sao_Tome', name: 'Africa/Sao_Tome' },
  { key: 'Africa/Tripoli', name: 'Africa/Tripoli' },
  { key: 'Africa/Tunis', name: 'Africa/Tunis' },
  { key: 'Africa/Windhoek', name: 'Africa/Windhoek' },
  { key: 'America/Adak', name: 'America/Adak' },
  { key: 'America/Anchorage', name: 'America/Anchorage' },
  { key: 'America/Anguilla', name: 'America/Anguilla' },
  { key: 'America/Antigua', name: 'America/Antigua' },
  { key: 'America/Araguaina', name: 'America/Araguaina' },
  {
    key: 'America/Argentina/Buenos_Aires',
    name: 'America/Argentina/Buenos_Aires',
  },
  { key: 'America/Argentina/Catamarca', name: 'America/Argentina/Catamarca' },
  { key: 'America/Argentina/Cordoba', name: 'America/Argentina/Cordoba' },
  { key: 'America/Argentina/Jujuy', name: 'America/Argentina/Jujuy' },
  { key: 'America/Argentina/La_Rioja', name: 'America/Argentina/La_Rioja' },
  { key: 'America/Argentina/Mendoza', name: 'America/Argentina/Mendoza' },
  {
    key: 'America/Argentina/Rio_Gallegos',
    name: 'America/Argentina/Rio_Gallegos',
  },
  { key: 'America/Argentina/Salta', name: 'America/Argentina/Salta' },
  { key: 'America/Argentina/San_Juan', name: 'America/Argentina/San_Juan' },
  { key: 'America/Argentina/San_Luis', name: 'America/Argentina/San_Luis' },
  { key: 'America/Argentina/Tucuman', name: 'America/Argentina/Tucuman' },
  { key: 'America/Argentina/Ushuaia', name: 'America/Argentina/Ushuaia' },
  { key: 'America/Aruba', name: 'America/Aruba' },
  { key: 'America/Asuncion', name: 'America/Asuncion' },
  { key: 'America/Atikokan', name: 'America/Atikokan' },
  { key: 'America/Bahia', name: 'America/Bahia' },
  { key: 'America/Bahia_Banderas', name: 'America/Bahia_Banderas' },
  { key: 'America/Barbados', name: 'America/Barbados' },
  { key: 'America/Belem', name: 'America/Belem' },
  { key: 'America/Belize', name: 'America/Belize' },
  { key: 'America/Blanc-Sablon', name: 'America/Blanc-Sablon' },
  { key: 'America/Boa_Vista', name: 'America/Boa_Vista' },
  { key: 'America/Bogota', name: 'America/Bogota' },
  { key: 'America/Boise', name: 'America/Boise' },
  { key: 'America/Cambridge_Bay', name: 'America/Cambridge_Bay' },
  { key: 'America/Campo_Grande', name: 'America/Campo_Grande' },
  { key: 'America/Cancun', name: 'America/Cancun' },
  { key: 'America/Caracas', name: 'America/Caracas' },
  { key: 'America/Cayenne', name: 'America/Cayenne' },
  { key: 'America/Cayman', name: 'America/Cayman' },
  { key: 'America/Chicago', name: 'America/Chicago' },
  { key: 'America/Chihuahua', name: 'America/Chihuahua' },
  { key: 'America/Costa_Rica', name: 'America/Costa_Rica' },
  { key: 'America/Creston', name: 'America/Creston' },
  { key: 'America/Cuiaba', name: 'America/Cuiaba' },
  { key: 'America/Curacao', name: 'America/Curacao' },
  { key: 'America/Danmarkshavn', name: 'America/Danmarkshavn' },
  { key: 'America/Dawson', name: 'America/Dawson' },
  { key: 'America/Dawson_Creek', name: 'America/Dawson_Creek' },
  { key: 'America/Denver', name: 'America/Denver' },
  { key: 'America/Detroit', name: 'America/Detroit' },
  { key: 'America/Dominica', name: 'America/Dominica' },
  { key: 'America/Edmonton', name: 'America/Edmonton' },
  { key: 'America/Eirunepe', name: 'America/Eirunepe' },
  { key: 'America/El_Salvador', name: 'America/El_Salvador' },
  { key: 'America/Fort_Nelson', name: 'America/Fort_Nelson' },
  { key: 'America/Fortaleza', name: 'America/Fortaleza' },
  { key: 'America/Glace_Bay', name: 'America/Glace_Bay' },
  { key: 'America/Goose_Bay', name: 'America/Goose_Bay' },
  { key: 'America/Grand_Turk', name: 'America/Grand_Turk' },
  { key: 'America/Grenada', name: 'America/Grenada' },
  { key: 'America/Guadeloupe', name: 'America/Guadeloupe' },
  { key: 'America/Guatemala', name: 'America/Guatemala' },
  { key: 'America/Guayaquil', name: 'America/Guayaquil' },
  { key: 'America/Guyana', name: 'America/Guyana' },
  { key: 'America/Halifax', name: 'America/Halifax' },
  { key: 'America/Havana', name: 'America/Havana' },
  { key: 'America/Hermosillo', name: 'America/Hermosillo' },
  {
    key: 'America/Indiana/Indianapolis',
    name: 'America/Indiana/Indianapolis',
  },
  { key: 'America/Indiana/Knox', name: 'America/Indiana/Knox' },
  { key: 'America/Indiana/Marengo', name: 'America/Indiana/Marengo' },
  { key: 'America/Indiana/Petersburg', name: 'America/Indiana/Petersburg' },
  { key: 'America/Indiana/Tell_City', name: 'America/Indiana/Tell_City' },
  { key: 'America/Indiana/Vevay', name: 'America/Indiana/Vevay' },
  { key: 'America/Indiana/Vincennes', name: 'America/Indiana/Vincennes' },
  { key: 'America/Indiana/Winamac', name: 'America/Indiana/Winamac' },
  { key: 'America/Inuvik', name: 'America/Inuvik' },
  { key: 'America/Iqaluit', name: 'America/Iqaluit' },
  { key: 'America/Jamaica', name: 'America/Jamaica' },
  { key: 'America/Juneau', name: 'America/Juneau' },
  { key: 'America/Kentucky/Louisville', name: 'America/Kentucky/Louisville' },
  { key: 'America/Kentucky/Monticello', name: 'America/Kentucky/Monticello' },
  { key: 'America/Kralendijk', name: 'America/Kralendijk' },
  { key: 'America/La_Paz', name: 'America/La_Paz' },
  { key: 'America/Lima', name: 'America/Lima' },
  { key: 'America/Los_Angeles', name: 'America/Los_Angeles' },
  { key: 'America/Lower_Princes', name: 'America/Lower_Princes' },
  { key: 'America/Maceio', name: 'America/Maceio' },
  { key: 'America/Managua', name: 'America/Managua' },
  { key: 'America/Manaus', name: 'America/Manaus' },
  { key: 'America/Marigot', name: 'America/Marigot' },
  { key: 'America/Martinique', name: 'America/Martinique' },
  { key: 'America/Matamoros', name: 'America/Matamoros' },
  { key: 'America/Mazatlan', name: 'America/Mazatlan' },
  { key: 'America/Menominee', name: 'America/Menominee' },
  { key: 'America/Merida', name: 'America/Merida' },
  { key: 'America/Metlakatla', name: 'America/Metlakatla' },
  { key: 'America/Mexico_City', name: 'America/Mexico_City' },
  { key: 'America/Miquelon', name: 'America/Miquelon' },
  { key: 'America/Moncton', name: 'America/Moncton' },
  { key: 'America/Monterrey', name: 'America/Monterrey' },
  { key: 'America/Montevideo', name: 'America/Montevideo' },
  { key: 'America/Montserrat', name: 'America/Montserrat' },
  { key: 'America/Nassau', name: 'America/Nassau' },
  { key: 'America/New_York', name: 'America/New_York' },
  { key: 'America/Nipigon', name: 'America/Nipigon' },
  { key: 'America/Nome', name: 'America/Nome' },
  { key: 'America/Noronha', name: 'America/Noronha' },
  { key: 'America/North_Dakota/Beulah', name: 'America/North_Dakota/Beulah' },
  { key: 'America/North_Dakota/Center', name: 'America/North_Dakota/Center' },
  {
    key: 'America/North_Dakota/New_Salem',
    name: 'America/North_Dakota/New_Salem',
  },
  { key: 'America/Nuuk', name: 'America/Nuuk' },
  { key: 'America/Ojinaga', name: 'America/Ojinaga' },
  { key: 'America/Panama', name: 'America/Panama' },
  { key: 'America/Pangnirtung', name: 'America/Pangnirtung' },
  { key: 'America/Paramaribo', name: 'America/Paramaribo' },
  { key: 'America/Phoenix', name: 'America/Phoenix' },
  { key: 'America/Port-au-Prince', name: 'America/Port-au-Prince' },
  { key: 'America/Port_of_Spain', name: 'America/Port_of_Spain' },
  { key: 'America/Porto_Velho', name: 'America/Porto_Velho' },
  { key: 'America/Puerto_Rico', name: 'America/Puerto_Rico' },
  { key: 'America/Punta_Arenas', name: 'America/Punta_Arenas' },
  { key: 'America/Rainy_River', name: 'America/Rainy_River' },
  { key: 'America/Rankin_Inlet', name: 'America/Rankin_Inlet' },
  { key: 'America/Recife', name: 'America/Recife' },
  { key: 'America/Regina', name: 'America/Regina' },
  { key: 'America/Resolute', name: 'America/Resolute' },
  { key: 'America/Rio_Branco', name: 'America/Rio_Branco' },
  { key: 'America/Santarem', name: 'America/Santarem' },
  { key: 'America/Santiago', name: 'America/Santiago' },
  { key: 'America/Santo_Domingo', name: 'America/Santo_Domingo' },
  { key: 'America/Sao_Paulo', name: 'America/Sao_Paulo' },
  { key: 'America/Scoresbysund', name: 'America/Scoresbysund' },
  { key: 'America/Sitka', name: 'America/Sitka' },
  { key: 'America/St_Barthelemy', name: 'America/St_Barthelemy' },
  { key: 'America/St_Johns', name: 'America/St_Johns' },
  { key: 'America/St_Kitts', name: 'America/St_Kitts' },
  { key: 'America/St_Lucia', name: 'America/St_Lucia' },
  { key: 'America/St_Thomas', name: 'America/St_Thomas' },
  { key: 'America/St_Vincent', name: 'America/St_Vincent' },
  { key: 'America/Swift_Current', name: 'America/Swift_Current' },
  { key: 'America/Tegucigalpa', name: 'America/Tegucigalpa' },
  { key: 'America/Thule', name: 'America/Thule' },
  { key: 'America/Thunder_Bay', name: 'America/Thunder_Bay' },
  { key: 'America/Tijuana', name: 'America/Tijuana' },
  { key: 'America/Toronto', name: 'America/Toronto' },
  { key: 'America/Tortola', name: 'America/Tortola' },
  { key: 'America/Vancouver', name: 'America/Vancouver' },
  { key: 'America/Whitehorse', name: 'America/Whitehorse' },
  { key: 'America/Winnipeg', name: 'America/Winnipeg' },
  { key: 'America/Yakutat', name: 'America/Yakutat' },
  { key: 'America/Yellowknife', name: 'America/Yellowknife' },
  { key: 'Antarctica/Casey', name: 'Antarctica/Casey' },
  { key: 'Antarctica/Davis', name: 'Antarctica/Davis' },
  { key: 'Antarctica/DumontDUrville', name: 'Antarctica/DumontDUrville' },
  { key: 'Antarctica/Macquarie', name: 'Antarctica/Macquarie' },
  { key: 'Antarctica/Mawson', name: 'Antarctica/Mawson' },
  { key: 'Antarctica/McMurdo', name: 'Antarctica/McMurdo' },
  { key: 'Antarctica/Palmer', name: 'Antarctica/Palmer' },
  { key: 'Antarctica/Rothera', name: 'Antarctica/Rothera' },
  { key: 'Antarctica/Syowa', name: 'Antarctica/Syowa' },
  { key: 'Antarctica/Troll', name: 'Antarctica/Troll' },
  { key: 'Antarctica/Vostok', name: 'Antarctica/Vostok' },
  { key: 'Arctic/Longyearbyen', name: 'Arctic/Longyearbyen' },
  { key: 'Asia/Aden', name: 'Asia/Aden' },
  { key: 'Asia/Almaty', name: 'Asia/Almaty' },
  { key: 'Asia/Amman', name: 'Asia/Amman' },
  { key: 'Asia/Anadyr', name: 'Asia/Anadyr' },
  { key: 'Asia/Aqtau', name: 'Asia/Aqtau' },
  { key: 'Asia/Aqtobe', name: 'Asia/Aqtobe' },
  { key: 'Asia/Ashgabat', name: 'Asia/Ashgabat' },
  { key: 'Asia/Atyrau', name: 'Asia/Atyrau' },
  { key: 'Asia/Baghdad', name: 'Asia/Baghdad' },
  { key: 'Asia/Bahrain', name: 'Asia/Bahrain' },
  { key: 'Asia/Baku', name: 'Asia/Baku' },
  { key: 'Asia/Bangkok', name: 'Asia/Bangkok' },
  { key: 'Asia/Barnaul', name: 'Asia/Barnaul' },
  { key: 'Asia/Beirut', name: 'Asia/Beirut' },
  { key: 'Asia/Bishkek', name: 'Asia/Bishkek' },
  { key: 'Asia/Brunei', name: 'Asia/Brunei' },
  { key: 'Asia/Chita', name: 'Asia/Chita' },
  { key: 'Asia/Choibalsan', name: 'Asia/Choibalsan' },
  { key: 'Asia/Colombo', name: 'Asia/Colombo' },
  { key: 'Asia/Damascus', name: 'Asia/Damascus' },
  { key: 'Asia/Dhaka', name: 'Asia/Dhaka' },
  { key: 'Asia/Dili', name: 'Asia/Dili' },
  { key: 'Asia/Dubai', name: 'Asia/Dubai' },
  { key: 'Asia/Dushanbe', name: 'Asia/Dushanbe' },
  { key: 'Asia/Famagusta', name: 'Asia/Famagusta' },
  { key: 'Asia/Gaza', name: 'Asia/Gaza' },
  { key: 'Asia/Hebron', name: 'Asia/Hebron' },
  { key: 'Asia/Ho_Chi_Minh', name: 'Asia/Ho_Chi_Minh' },
  { key: 'Asia/Hong_Kong', name: 'Asia/Hong_Kong' },
  { key: 'Asia/Hovd', name: 'Asia/Hovd' },
  { key: 'Asia/Irkutsk', name: 'Asia/Irkutsk' },
  { key: 'Asia/Jakarta', name: 'Asia/Jakarta' },
  { key: 'Asia/Jayapura', name: 'Asia/Jayapura' },
  { key: 'Asia/Jerusalem', name: 'Asia/Jerusalem' },
  { key: 'Asia/Kabul', name: 'Asia/Kabul' },
  { key: 'Asia/Kamchatka', name: 'Asia/Kamchatka' },
  { key: 'Asia/Karachi', name: 'Asia/Karachi' },
  { key: 'Asia/Kathmandu', name: 'Asia/Kathmandu' },
  { key: 'Asia/Khandyga', name: 'Asia/Khandyga' },
  { key: 'Asia/Kolkata', name: 'Asia/Kolkata' },
  { key: 'Asia/Krasnoyarsk', name: 'Asia/Krasnoyarsk' },
  { key: 'Asia/Kuala_Lumpur', name: 'Asia/Kuala_Lumpur' },
  { key: 'Asia/Kuching', name: 'Asia/Kuching' },
  { key: 'Asia/Kuwait', name: 'Asia/Kuwait' },
  { key: 'Asia/Macau', name: 'Asia/Macau' },
  { key: 'Asia/Magadan', name: 'Asia/Magadan' },
  { key: 'Asia/Makassar', name: 'Asia/Makassar' },
  { key: 'Asia/Manila', name: 'Asia/Manila' },
  { key: 'Asia/Muscat', name: 'Asia/Muscat' },
  { key: 'Asia/Nicosia', name: 'Asia/Nicosia' },
  { key: 'Asia/Novokuznetsk', name: 'Asia/Novokuznetsk' },
  { key: 'Asia/Novosibirsk', name: 'Asia/Novosibirsk' },
  { key: 'Asia/Omsk', name: 'Asia/Omsk' },
  { key: 'Asia/Oral', name: 'Asia/Oral' },
  { key: 'Asia/Phnom_Penh', name: 'Asia/Phnom_Penh' },
  { key: 'Asia/Pontianak', name: 'Asia/Pontianak' },
  { key: 'Asia/Pyongyang', name: 'Asia/Pyongyang' },
  { key: 'Asia/Qatar', name: 'Asia/Qatar' },
  { key: 'Asia/Qostanay', name: 'Asia/Qostanay' },
  { key: 'Asia/Qyzylorda', name: 'Asia/Qyzylorda' },
  { key: 'Asia/Riyadh', name: 'Asia/Riyadh' },
  { key: 'Asia/Sakhalin', name: 'Asia/Sakhalin' },
  { key: 'Asia/Samarkand', name: 'Asia/Samarkand' },
  { key: 'Asia/Seoul', name: 'Asia/Seoul' },
  { key: 'Asia/Shanghai', name: 'Asia/Shanghai' },
  { key: 'Asia/Singapore', name: 'Asia/Singapore' },
  { key: 'Asia/Srednekolymsk', name: 'Asia/Srednekolymsk' },
  { key: 'Asia/Taipei', name: 'Asia/Taipei' },
  { key: 'Asia/Tashkent', name: 'Asia/Tashkent' },
  { key: 'Asia/Tbilisi', name: 'Asia/Tbilisi' },
  { key: 'Asia/Tehran', name: 'Asia/Tehran' },
  { key: 'Asia/Thimphu', name: 'Asia/Thimphu' },
  { key: 'Asia/Tokyo', name: 'Asia/Tokyo' },
  { key: 'Asia/Tomsk', name: 'Asia/Tomsk' },
  { key: 'Asia/Ulaanbaatar', name: 'Asia/Ulaanbaatar' },
  { key: 'Asia/Urumqi', name: 'Asia/Urumqi' },
  { key: 'Asia/Ust-Nera', name: 'Asia/Ust-Nera' },
  { key: 'Asia/Vientiane', name: 'Asia/Vientiane' },
  { key: 'Asia/Vladivostok', name: 'Asia/Vladivostok' },
  { key: 'Asia/Yakutsk', name: 'Asia/Yakutsk' },
  { key: 'Asia/Yangon', name: 'Asia/Yangon' },
  { key: 'Asia/Yekaterinburg', name: 'Asia/Yekaterinburg' },
  { key: 'Asia/Yerevan', name: 'Asia/Yerevan' },
  { key: 'Atlantic/Azores', name: 'Atlantic/Azores' },
  { key: 'Atlantic/Bermuda', name: 'Atlantic/Bermuda' },
  { key: 'Atlantic/Canary', name: 'Atlantic/Canary' },
  { key: 'Atlantic/Cape_Verde', name: 'Atlantic/Cape_Verde' },
  { key: 'Atlantic/Faroe', name: 'Atlantic/Faroe' },
  { key: 'Atlantic/Madeira', name: 'Atlantic/Madeira' },
  { key: 'Atlantic/Reykjavik', name: 'Atlantic/Reykjavik' },
  { key: 'Atlantic/South_Georgia', name: 'Atlantic/South_Georgia' },
  { key: 'Atlantic/St_Helena', name: 'Atlantic/St_Helena' },
  { key: 'Atlantic/Stanley', name: 'Atlantic/Stanley' },
  { key: 'Australia/Adelaide', name: 'Australia/Adelaide' },
  { key: 'Australia/Brisbane', name: 'Australia/Brisbane' },
  { key: 'Australia/Broken_Hill', name: 'Australia/Broken_Hill' },
  { key: 'Australia/Darwin', name: 'Australia/Darwin' },
  { key: 'Australia/Eucla', name: 'Australia/Eucla' },
  { key: 'Australia/Hobart', name: 'Australia/Hobart' },
  { key: 'Australia/Lindeman', name: 'Australia/Lindeman' },
  { key: 'Australia/Lord_Howe', name: 'Australia/Lord_Howe' },
  { key: 'Australia/Melbourne', name: 'Australia/Melbourne' },
  { key: 'Australia/Perth', name: 'Australia/Perth' },
  { key: 'Australia/Sydney', name: 'Australia/Sydney' },
  { key: 'Europe/Amsterdam', name: 'Europe/Amsterdam' },
  { key: 'Europe/Andorra', name: 'Europe/Andorra' },
  { key: 'Europe/Astrakhan', name: 'Europe/Astrakhan' },
  { key: 'Europe/Athens', name: 'Europe/Athens' },
  { key: 'Europe/Belgrade', name: 'Europe/Belgrade' },
  { key: 'Europe/Berlin', name: 'Europe/Berlin' },
  { key: 'Europe/Bratislava', name: 'Europe/Bratislava' },
  { key: 'Europe/Brussels', name: 'Europe/Brussels' },
  { key: 'Europe/Bucharest', name: 'Europe/Bucharest' },
  { key: 'Europe/Budapest', name: 'Europe/Budapest' },
  { key: 'Europe/Busingen', name: 'Europe/Busingen' },
  { key: 'Europe/Chisinau', name: 'Europe/Chisinau' },
  { key: 'Europe/Copenhagen', name: 'Europe/Copenhagen' },
  { key: 'Europe/Dublin', name: 'Europe/Dublin' },
  { key: 'Europe/Gibraltar', name: 'Europe/Gibraltar' },
  { key: 'Europe/Guernsey', name: 'Europe/Guernsey' },
  { key: 'Europe/Helsinki', name: 'Europe/Helsinki' },
  { key: 'Europe/Isle_of_Man', name: 'Europe/Isle_of_Man' },
  { key: 'Europe/Istanbul', name: 'Europe/Istanbul' },
  { key: 'Europe/Jersey', name: 'Europe/Jersey' },
  { key: 'Europe/Kaliningrad', name: 'Europe/Kaliningrad' },
  { key: 'Europe/Kiev', name: 'Europe/Kiev' },
  { key: 'Europe/Kirov', name: 'Europe/Kirov' },
  { key: 'Europe/Lisbon', name: 'Europe/Lisbon' },
  { key: 'Europe/Ljubljana', name: 'Europe/Ljubljana' },
  { key: 'Europe/London', name: 'Europe/London' },
  { key: 'Europe/Luxembourg', name: 'Europe/Luxembourg' },
  { key: 'Europe/Madrid', name: 'Europe/Madrid' },
  { key: 'Europe/Malta', name: 'Europe/Malta' },
  { key: 'Europe/Mariehamn', name: 'Europe/Mariehamn' },
  { key: 'Europe/Minsk', name: 'Europe/Minsk' },
  { key: 'Europe/Monaco', name: 'Europe/Monaco' },
  { key: 'Europe/Moscow', name: 'Europe/Moscow' },
  { key: 'Europe/Oslo', name: 'Europe/Oslo' },
  { key: 'Europe/Paris', name: 'Europe/Paris' },
  { key: 'Europe/Podgorica', name: 'Europe/Podgorica' },
  { key: 'Europe/Prague', name: 'Europe/Prague' },
  { key: 'Europe/Riga', name: 'Europe/Riga' },
  { key: 'Europe/Rome', name: 'Europe/Rome' },
  { key: 'Europe/Samara', name: 'Europe/Samara' },
  { key: 'Europe/San_Marino', name: 'Europe/San_Marino' },
  { key: 'Europe/Sarajevo', name: 'Europe/Sarajevo' },
  { key: 'Europe/Saratov', name: 'Europe/Saratov' },
  { key: 'Europe/Simferopol', name: 'Europe/Simferopol' },
  { key: 'Europe/Skopje', name: 'Europe/Skopje' },
  { key: 'Europe/Sofia', name: 'Europe/Sofia' },
  { key: 'Europe/Stockholm', name: 'Europe/Stockholm' },
  { key: 'Europe/Tallinn', name: 'Europe/Tallinn' },
  { key: 'Europe/Tirane', name: 'Europe/Tirane' },
  { key: 'Europe/Ulyanovsk', name: 'Europe/Ulyanovsk' },
  { key: 'Europe/Uzhgorod', name: 'Europe/Uzhgorod' },
  { key: 'Europe/Vaduz', name: 'Europe/Vaduz' },
  { key: 'Europe/Vatican', name: 'Europe/Vatican' },
  { key: 'Europe/Vienna', name: 'Europe/Vienna' },
  { key: 'Europe/Vilnius', name: 'Europe/Vilnius' },
  { key: 'Europe/Volgograd', name: 'Europe/Volgograd' },
  { key: 'Europe/Warsaw', name: 'Europe/Warsaw' },
  { key: 'Europe/Zagreb', name: 'Europe/Zagreb' },
  { key: 'Europe/Zaporozhye', name: 'Europe/Zaporozhye' },
  { key: 'Europe/Zurich', name: 'Europe/Zurich' },
  { key: 'Indian/Antananarivo', name: 'Indian/Antananarivo' },
  { key: 'Indian/Chagos', name: 'Indian/Chagos' },
  { key: 'Indian/Christmas', name: 'Indian/Christmas' },
  { key: 'Indian/Cocos', name: 'Indian/Cocos' },
  { key: 'Indian/Comoro', name: 'Indian/Comoro' },
  { key: 'Indian/Kerguelen', name: 'Indian/Kerguelen' },
  { key: 'Indian/Mahe', name: 'Indian/Mahe' },
  { key: 'Indian/Maldives', name: 'Indian/Maldives' },
  { key: 'Indian/Mauritius', name: 'Indian/Mauritius' },
  { key: 'Indian/Mayotte', name: 'Indian/Mayotte' },
  { key: 'Indian/Reunion', name: 'Indian/Reunion' },
  { key: 'Pacific/Apia', name: 'Pacific/Apia' },
  { key: 'Pacific/Auckland', name: 'Pacific/Auckland' },
  { key: 'Pacific/Bougainville', name: 'Pacific/Bougainville' },
  { key: 'Pacific/Chatham', name: 'Pacific/Chatham' },
  { key: 'Pacific/Chuuk', name: 'Pacific/Chuuk' },
  { key: 'Pacific/Easter', name: 'Pacific/Easter' },
  { key: 'Pacific/Efate', name: 'Pacific/Efate' },
  { key: 'Pacific/Enderbury', name: 'Pacific/Enderbury' },
  { key: 'Pacific/Fakaofo', name: 'Pacific/Fakaofo' },
  { key: 'Pacific/Fiji', name: 'Pacific/Fiji' },
  { key: 'Pacific/Funafuti', name: 'Pacific/Funafuti' },
  { key: 'Pacific/Galapagos', name: 'Pacific/Galapagos' },
  { key: 'Pacific/Gambier', name: 'Pacific/Gambier' },
  { key: 'Pacific/Guadalcanal', name: 'Pacific/Guadalcanal' },
  { key: 'Pacific/Guam', name: 'Pacific/Guam' },
  { key: 'Pacific/Honolulu', name: 'Pacific/Honolulu' },
  { key: 'Pacific/Kiritimati', name: 'Pacific/Kiritimati' },
  { key: 'Pacific/Kosrae', name: 'Pacific/Kosrae' },
  { key: 'Pacific/Kwajalein', name: 'Pacific/Kwajalein' },
  { key: 'Pacific/Majuro', name: 'Pacific/Majuro' },
  { key: 'Pacific/Marquesas', name: 'Pacific/Marquesas' },
  { key: 'Pacific/Midway', name: 'Pacific/Midway' },
  { key: 'Pacific/Nauru', name: 'Pacific/Nauru' },
  { key: 'Pacific/Niue', name: 'Pacific/Niue' },
  { key: 'Pacific/Norfolk', name: 'Pacific/Norfolk' },
  { key: 'Pacific/Noumea', name: 'Pacific/Noumea' },
  { key: 'Pacific/Pago_Pago', name: 'Pacific/Pago_Pago' },
  { key: 'Pacific/Palau', name: 'Pacific/Palau' },
  { key: 'Pacific/Pitcairn', name: 'Pacific/Pitcairn' },
  { key: 'Pacific/Pohnpei', name: 'Pacific/Pohnpei' },
  { key: 'Pacific/Port_Moresby', name: 'Pacific/Port_Moresby' },
  { key: 'Pacific/Rarotonga', name: 'Pacific/Rarotonga' },
  { key: 'Pacific/Saipan', name: 'Pacific/Saipan' },
  { key: 'Pacific/Tahiti', name: 'Pacific/Tahiti' },
  { key: 'Pacific/Tarawa', name: 'Pacific/Tarawa' },
  { key: 'Pacific/Tongatapu', name: 'Pacific/Tongatapu' },
  { key: 'Pacific/Wake', name: 'Pacific/Wake' },
  { key: 'Pacific/Wallis', name: 'Pacific/Wallis' },
  { key: 'UTC', name: 'UTC' },
];
